version: "3.3"
services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    volumes:
      - "./app:/code"
    depends_on:
      - pg_db
  pg_db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    volumes:
      - /pg_project:/var/lib/postgresql/data
    ports:
      - "5433:5432"
